LobbySignPrefix: "[ug lsign]"
ClickInputSignPrefix: "[ug cisign]"
RedstoneInputSignPrefix: "[ug risign]"
TextOutputSignPrefix: "[ug tosign]"
RedstoneOutputSignPrefix: "[ug rosign]"

Database:
  Type: "sqlite"
  Address: "127.0.0.1"
  Port: 3306
  User: "root"
  Password: ""
  Database: ""
  Prefix: "ug_"
