messages:
  prefix: "&8[&bUltimateGames&8]"
  
  games: {}
  
  arenas:
    select: "Punch two corners of a cuboid to create the Arena '%s' of Game '%s'."
    create: "Created Arena '%s' of Game '%s'."
    delete: "Removed Arena '%s' of Game '%s'."
    forceload: ""
    forceunload: ""
    start: "The game has started!"
    end: "The game has ended!"
    setstatus: "Set the status of Arena '%s' of Game '%s' to '%s'."
    forcestart: "Force started the Arena '%s' of Game '%s'."
    forcestop: "Force stopped the Arena '%s' of Game '%s'."

    join: "%s joined the game! %s"
    leave: "%s left the game! %s"

    alreadyexists: "Arena already exists."
    doesntexit: "Arena doesn't exist."
    failedtocreate: "Failed to create Arena '%s' of Game '%s'. %s"
    failedtojoin: "Failed to join Arena '%s' of Game '%s'. %s"

  queues:
    join: "Joined queue for Arena '%s' of Game '%s'. You are %s in line and will be able to join %s."
    leave: "Left queue for Arena '%s' of Game '%s'."
    arenacleared: "Queue for Arena '%s' of Game '%s' has been cleared."
    queuecleared: "All queues cleared."
    
  spawnpoints:
    create: "Created SpawnPoint for Arena '%s' of Game '%s'"
    leave: "You are not allowed to leave the spawnpoint."
  
  countdowns:
    timeleftstart: "The game starts in %s seconds!"
    timeleftend: "The game ends in %s seconds!"
    aborted: "Countdown aborted."
    
  protections:
    place: "You are not allowed to place blocks in the arena."
    break: "You are not allowed to break blocks in the arena."
    leave: "You are not allowed to go outside the arena."